// Property catalogue shared by the properties listing page and regional landing pages (e.g. Baja California).
import type { SavedProperty } from "@/hooks/useSavedProperties";

const CLD = "https://res.cloudinary.com/dserzvrwe/image/upload/f_auto,q_auto";

export type PropertyType = "Lots" | "Condos" | "Mixed";

export type Property = {
  id: string;
  title: string;
  zone: string;
  region: string;
  sqmMin: number;
  priceUSD: number;
  availability: "Available" | "Coming Soon";
  type: PropertyType;
  href: string;
  image: string;
  certified: boolean;
};

// Adapts a catalogue entry to the shared saved-properties store. The `catalog-` id prefix keeps
// the namespace separate from explore-map listings while staying stable across every card that
// renders the same development, so hearting it anywhere toggles it everywhere.
// Catalogue entries don't carry beds/baths — derive card-friendly values from the property type.
export function toSavedProperty(p: Property): SavedProperty {
  const isLots = p.type === "Lots";
  return {
    id: `catalog-${p.id}`,
    title: p.title,
    zone: p.zone,
    priceUSD: p.priceUSD,
    beds: isLots ? 0 : 2,
    baths: isLots ? 0 : 2,
    sqm: p.sqmMin,
    status: p.availability,
    image: p.image,
  };
}

export const properties: Property[] = [
  // City assignments follow the SEO content document (source of truth as of Jul 2026).
  {
    id: "delmar",
    title: "Del Mar Residencial",
    zone: "Tijuana, BC",
    region: "Tijuana",
    sqmMin: 250,
    priceUSD: 320000,
    availability: "Available",
    type: "Mixed",
    href: "/properties/delmar",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80",
    certified: true,
  },
  {
    id: "andares",
    title: "Andares",
    zone: "Tijuana, BC",
    region: "Tijuana",
    sqmMin: 85,
    priceUSD: 185000,
    availability: "Available",
    type: "Condos",
    href: "/properties/andares",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    certified: true,
  },
  {
    id: "alimar",
    title: "Alimar",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 140,
    priceUSD: 195000,
    availability: "Available",
    type: "Condos",
    href: "/properties/alimar",
    image: "https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80",
    certified: true,
  },
  {
    id: "torre51",
    title: "Tower 51",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 72,
    priceUSD: 165000,
    availability: "Available",
    type: "Condos",
    href: "/properties/torre51",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    certified: true,
  },
  {
    id: "tierra-de-agua",
    title: "Tierra de Agua",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 300,
    priceUSD: 280000,
    availability: "Available",
    type: "Lots",
    href: "/properties/tierra-de-agua",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    certified: true,
  },
  {
    id: "punta-piedra",
    title: "Punta Piedra",
    zone: "Ensenada, BC",
    region: "Ensenada",
    sqmMin: 350,
    priceUSD: 125000,
    availability: "Available",
    type: "Lots",
    href: "/properties/punta-piedra",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    certified: true,
  },
  {
    id: "palacio-del-mar",
    title: "Palacio del Mar",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 180,
    priceUSD: 520000,
    availability: "Available",
    type: "Mixed",
    href: "/properties/palacio-del-mar",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    certified: true,
  },
  {
    id: "naos",
    title: "Naos",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 200,
    priceUSD: 155000,
    availability: "Available",
    type: "Lots",
    href: "/properties/naos",
    image: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800&q=80",
    certified: false,
  },
  {
    id: "loma-serena",
    title: "Loma Serena",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 400,
    priceUSD: 145000,
    availability: "Available",
    type: "Lots",
    href: "/properties/loma-serena",
    image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&q=80",
    certified: true,
  },
  {
    id: "pacifica",
    title: "Pacifica",
    zone: "Ensenada, BC",
    region: "Ensenada",
    sqmMin: 300,
    priceUSD: 180000,
    availability: "Available",
    type: "Mixed",
    href: "/properties/pacifica",
    image: `${CLD}/pacifica/hero`,
    certified: true,
  },
  {
    id: "encanto-del-valle",
    title: "Encanto del Valle",
    zone: "Valle de Guadalupe, BC",
    region: "Ensenada",
    sqmMin: 450,
    priceUSD: 95000,
    availability: "Available",
    type: "Lots",
    href: "/properties/encanto-del-valle",
    image: `${CLD}/encanto-del-valle/safety`,
    certified: true,
  },
  {
    id: "laguna-bay",
    title: "Laguna Bay",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 180,
    priceUSD: 145000,
    availability: "Available",
    type: "Mixed",
    href: "/properties/laguna-bay",
    image: `${CLD}/laguna-bay/laguna-bay/lake`,
    certified: true,
  },
  {
    id: "costa-real",
    title: "Costa Real",
    zone: "Tijuana, BC",
    region: "Tijuana",
    sqmMin: 300,
    priceUSD: 220000,
    availability: "Available",
    type: "Mixed",
    href: "/properties/costa-real",
    image: `${CLD}/costa-real/hero`,
    certified: true,
  },
  {
    id: "costa-baja",
    title: "Costa Baja",
    zone: "Tijuana, BC",
    region: "Tijuana",
    sqmMin: 120,
    priceUSD: 427000,
    availability: "Available",
    type: "Condos",
    href: "/properties/costa-baja",
    image: `${CLD}/costa-baja/hero`,
    certified: true,
  },
  {
    id: "costa-bella",
    title: "Costa Bella",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 95,
    priceUSD: 210000,
    availability: "Available",
    type: "Condos",
    href: "/properties/costa-bella",
    image: `${CLD}/costa-bella/hero`,
    certified: true,
  },
  {
    id: "cibola-del-mar",
    title: "Cíbola del Mar",
    zone: "Ensenada, BC",
    region: "Ensenada",
    sqmMin: 100,
    priceUSD: 190000,
    availability: "Available",
    type: "Condos",
    href: "/properties/cibola-del-mar",
    image: `${CLD}/cibola-del-mar/hero`,
    certified: true,
  },
  {
    id: "the-wave",
    title: "The Wavve",
    zone: "Rosarito, BC",
    region: "Rosarito",
    sqmMin: 80,
    priceUSD: 175000,
    availability: "Available",
    type: "Condos",
    href: "/properties/the-wave",
    image: `${CLD}/the-wave/the-wave/hero`,
    certified: true,
  },
  {
    id: "valle",
    title: "Valle Dorado",
    zone: "Valle de Guadalupe, BC",
    region: "Valle de Guadalupe",
    sqmMin: 500,
    priceUSD: 110000,
    availability: "Coming Soon",
    type: "Lots",
    href: "/properties/valle",
    image: "https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?w=800&q=80",
    certified: false,
  },
];
