// Static blog data — swap for a CMS (Sanity is already a dependency) once real posts exist.
export const BLOG_CATEGORIES = ["All", "Guides", "Neighborhoods", "Finance", "Market", "Lifestyle"] as const;
export type BlogCategoryFilter = (typeof BLOG_CATEGORIES)[number];

// Article body is a flat list of blocks so paragraphs, headings, quotes, and images can be
// interleaved in any order — `heading` ids are what the "On this page" TOC links scroll to.
// Paragraph text supports a tiny markdown-lite syntax: **bold** and [label](href) — see RichText.
export type ContentBlock =
  | { type: "lead"; text: string }
  | { type: "heading"; id: string; text: string }
  | { type: "paragraph"; text: string }
  | { type: "quote"; text: string; author: string }
  | { type: "image"; src: string; caption: string };

export const posts = [
  {
    id: 1,
    slug: "2026-baja-california-buyers-report",
    title: "The 2026 Baja California Buyer's Report: prices, hotspots & what changed",
    excerpt:
      "Median prices, the fastest-moving corridors from Rosarito to Ensenada, and what the new certification rules mean for U.S. buyers this year.",
    dek: "Median prices, the fastest-moving corridors from Rosarito to Ensenada, and what the new certification rules mean for U.S. buyers this year.",
    category: "Market" as const,
    date: "Jun 2026",
    readTime: "9 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&q=80",
    featured: true,
    toc: [
      { id: "median-prices-by-corridor", label: "Median prices by corridor" },
      { id: "the-fastest-moving-zones", label: "The fastest-moving zones" },
      { id: "what-the-new-rules-change", label: "What the new rules change" },
    ],
    body: [
      { type: "lead", text: "Baja California's certified-listing market grew faster in the first half of 2026 than in any comparable period since Property Dreamz began tracking it." },
      { type: "heading", id: "median-prices-by-corridor", text: "Median prices by corridor" },
      { type: "paragraph", text: "Rosarito remains the most affordable oceanfront corridor, with median pre-sale pricing still under $2,600 per square meter. Ensenada and the Punta Banda coastline now command a meaningful premium over Rosarito, driven by tighter buildable coastline and fewer active projects." },
      { type: "heading", id: "the-fastest-moving-zones", text: "The fastest-moving zones" },
      { type: "paragraph", text: "**Zona Río in Tijuana** and the Rosarito beachfront absorbed inventory fastest this year, with several certified developments selling out their first release phase within 90 days of launch." },
      { type: "heading", id: "what-the-new-rules-change", text: "What the new rules change" },
      { type: "paragraph", text: "New state-level certification requirements now mandate a third-party HOA reserve audit before a development can be marketed to foreign buyers — a rule Property Dreamz had already been applying to every [certified](/about) listing." },
    ] as ContentBlock[],
  },
  {
    id: 2,
    slug: "fideicomiso-explained",
    title: "The fideicomiso, explained: buying in Mexico's restricted zone",
    excerpt: "How the bank-trust structure works, what it costs, and why it's the standard path for foreign buyers near the coast.",
    dek: "A plain-English guide to the bank trust that lets foreigners hold beachfront title in Baja California — how it works, what it costs, and how long it takes.",
    category: "Guides" as const,
    date: "Jun 2026",
    readTime: "7 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    featured: false,
    toc: [
      { id: "what-is-a-fideicomiso", label: "What is a fideicomiso?" },
      { id: "why-the-restricted-zone-exists", label: "Why the restricted zone exists" },
      { id: "setting-it-up-step-by-step", label: "Setting it up, step by step" },
      { id: "costs-and-timeline", label: "Costs and timeline" },
      { id: "key-takeaways", label: "Key takeaways" },
    ],
    body: [
      { type: "lead", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." },
      { type: "heading", id: "what-is-a-fideicomiso", text: "What is a fideicomiso?" },
      {
        type: "paragraph",
        text: "Baja California is one of the most sought-after destinations for Americans and Canadians **buying property in Mexico**. With its stunning Pacific coastline, thriving border economy, and proximity to San Diego, cities like [Tijuana](/explore-map?search=Tijuana), [Ensenada](/explore-map?search=Ensenada), and [Rosarito](/explore-map?search=Rosarito) offer exceptional value for buyers at every budget. Whether you are searching for a **beachfront condo**, a gated community home, or a vacation retreat, [Baja California real estate](/properties) delivers world-class lifestyle options backed by a strong legal framework for foreign ownership. All developments listed on **Property Dreamz** are [certified](/about) — every title has been searched, every developer background-checked, and every **HOA reserve audited** before a single property goes live on our platform. Investing in [Baja California real estate](/properties) has never been more transparent or secure.",
      },
      { type: "paragraph", text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
      { type: "heading", id: "why-the-restricted-zone-exists", text: "Why the restricted zone exists" },
      { type: "paragraph", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." },
      { type: "quote", text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", author: "Laura Méndez, Certified Mexico Real Estate" },
      { type: "heading", id: "setting-it-up-step-by-step", text: "Setting it up, step by step" },
      { type: "paragraph", text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
      { type: "image", src: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200&q=80", caption: "Beachfront developments in Rosarito, where fideicomiso title is standard for foreign buyers." },
      { type: "heading", id: "costs-and-timeline", text: "Costs and timeline" },
      { type: "paragraph", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." },
      { type: "heading", id: "key-takeaways", text: "Key takeaways" },
      { type: "paragraph", text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." },
    ] as ContentBlock[],
  },
  {
    id: 3,
    slug: "rosarito-vs-ensenada",
    title: "Rosarito vs. Ensenada: where to buy your beachfront condo",
    excerpt: "Comparing the two corridors on price per meter, drive time to the border, and the pace of new development.",
    dek: "Comparing the two corridors on price per meter, drive time to the border, and the pace of new development.",
    category: "Neighborhoods" as const,
    date: "Jun 2026",
    readTime: "6 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80",
    featured: false,
    toc: [
      { id: "price-per-meter", label: "Price per square meter" },
      { id: "commute-and-border-access", label: "Commute and border access" },
      { id: "which-one-fits-you", label: "Which one fits you" },
    ],
    body: [
      { type: "lead", text: "Rosarito and Ensenada sit less than an hour apart on the same coastline, but they attract very different kinds of buyers." },
      { type: "heading", id: "price-per-meter", text: "Price per square meter" },
      { type: "paragraph", text: "Rosarito's beachfront towers still price below $2,500 per square meter in most pre-sale developments, while Ensenada's boutique condo market runs closer to $3,200 thanks to tighter supply and a smaller buildable coastline." },
      { type: "heading", id: "commute-and-border-access", text: "Commute and border access" },
      { type: "paragraph", text: "Rosarito sits roughly 20 minutes from the San Ysidro border crossing, making it the default choice for weekend owners. Ensenada is a further 90 minutes south, which filters for buyers planning to relocate rather than commute." },
      { type: "heading", id: "which-one-fits-you", text: "Which one fits you" },
      { type: "paragraph", text: "If you want a low-maintenance weekend property near the border, Rosarito wins on convenience. If you're after a quieter, more established town with a real local economy beyond tourism, Ensenada is the stronger long-term bet." },
    ] as ContentBlock[],
  },
  {
    id: 4,
    slug: "closing-costs-and-taxes",
    title: "Closing costs and taxes for U.S. buyers in Baja California",
    excerpt: "A line-by-line breakdown of notary fees, acquisition tax, and the annual property tax you'll actually pay.",
    dek: "A line-by-line look at what actually shows up on a Baja California closing statement, from notary fees to the annual property tax bill.",
    category: "Finance" as const,
    date: "May 2026",
    readTime: "5 min read",
    author: "Chris Doyle",
    authorRole: "Cross-Border Living Editor",
    authorInitials: "CD",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    featured: false,
    toc: [
      { id: "one-time-closing-costs", label: "One-time closing costs" },
      { id: "the-fideicomiso-fee", label: "The fideicomiso fee" },
      { id: "ongoing-property-taxes", label: "Ongoing property taxes" },
    ],
    body: [
      { type: "lead", text: "Most first-time buyers underestimate closing costs in Mexico because the categories don't map cleanly onto a U.S. settlement statement." },
      { type: "heading", id: "one-time-closing-costs", text: "One-time closing costs" },
      { type: "paragraph", text: "Expect to budget 5-7% of the purchase price for acquisition tax, notary fees, and registration — roughly double what a comparable U.S. closing would run." },
      { type: "heading", id: "the-fideicomiso-fee", text: "The fideicomiso fee" },
      { type: "paragraph", text: "If the property sits in the restricted zone, add a one-time bank-trust setup fee plus an annual trustee fee, typically $500-$700 USD per year. See our [fideicomiso guide](/blog/fideicomiso-explained) for the full structure." },
      { type: "heading", id: "ongoing-property-taxes", text: "Ongoing property taxes" },
      { type: "paragraph", text: "Predial, Mexico's annual property tax, is calculated on assessed value rather than market value and is usually a fraction of what U.S. owners are used to paying." },
    ] as ContentBlock[],
  },
  {
    id: 5,
    slug: "oceanfront-developments-under-300k",
    title: "Top oceanfront developments under $300k in 2026",
    excerpt: "Six certified developments with unit prices still under $300k USD — and how long that's likely to last.",
    dek: "Six certified developments where oceanfront or ocean-view units are still priced under $300,000 USD — for now.",
    category: "Market" as const,
    date: "May 2026",
    readTime: "8 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80",
    featured: false,
    toc: [
      { id: "why-prices-are-still-low", label: "Why prices are still low" },
      { id: "the-six-developments", label: "The six developments" },
      { id: "how-long-this-will-last", label: "How long this will last" },
    ],
    body: [
      { type: "lead", text: "Oceanfront pricing under $300k is disappearing fastest in Rosarito and holding on longest in a handful of pre-sale phases further south." },
      { type: "heading", id: "why-prices-are-still-low", text: "Why prices are still low" },
      { type: "paragraph", text: "Early construction phases price below finished inventory, and several **certified developers** are still selling initial releases well below their projected completion value." },
      { type: "heading", id: "the-six-developments", text: "The six developments" },
      { type: "paragraph", text: "The current list spans [Rosarito](/explore-map?search=Rosarito), Ensenada, and Puerto Nuevo, weighted toward one- and two-bedroom units in mid-rise buildings with completion dates in 2027 and 2028." },
      { type: "heading", id: "how-long-this-will-last", text: "How long this will last" },
      { type: "paragraph", text: "Based on absorption rates over the last three delivery cycles, sub-$300k oceanfront inventory in these corridors has historically sold out within 12-18 months of a project's public launch." },
    ] as ContentBlock[],
  },
  {
    id: 6,
    slug: "what-certified-development-means",
    title: "What a 'certified development' really means on Property Dreamz",
    excerpt: "Every listing goes through legal, regulatory, and security review before it's certified. Here's the checklist.",
    dek: "Every listing on Property Dreamz goes through the same certification checklist before it's allowed to go live. Here's exactly what that means.",
    category: "Trust" as const,
    date: "Apr 2026",
    readTime: "4 min read",
    author: "Diego Alvarado",
    authorRole: "Legal & Compliance Editor",
    authorInitials: "DA",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    featured: false,
    toc: [
      { id: "title-search", label: "Title search" },
      { id: "developer-background-check", label: "Developer background check" },
      { id: "hoa-reserve-audit", label: "HOA reserve audit" },
    ],
    body: [
      { type: "lead", text: "'Certified' is not a marketing label on Property Dreamz — it's a specific, repeatable review process every development has to pass." },
      { type: "heading", id: "title-search", text: "Title search" },
      { type: "paragraph", text: "A local notario público confirms the title is clean, correctly registered, and free of liens before a listing is published." },
      { type: "heading", id: "developer-background-check", text: "Developer background check" },
      { type: "paragraph", text: "We review a developer's delivery history, litigation record, and regulatory standing with state and federal authorities." },
      { type: "heading", id: "hoa-reserve-audit", text: "HOA reserve audit" },
      { type: "paragraph", text: "For completed communities, we audit HOA reserve funding to flag developments likely to hit buyers with surprise special assessments." },
    ] as ContentBlock[],
  },
  {
    id: 7,
    slug: "30-minutes-from-san-diego",
    title: "30 minutes from San Diego: the cross-border lifestyle",
    excerpt: "What daily life actually looks like for Americans who split time between San Diego and Baja California.",
    dek: "What daily life actually looks like for Americans splitting time between San Diego and Baja California.",
    category: "Lifestyle" as const,
    date: "Apr 2026",
    readTime: "6 min read",
    author: "Chris Doyle",
    authorRole: "Cross-Border Living Editor",
    authorInitials: "CD",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    featured: false,
    toc: [
      { id: "the-daily-commute", label: "The daily commute" },
      { id: "cost-of-living", label: "Cost of living" },
      { id: "building-a-routine", label: "Building a routine" },
    ],
    body: [
      { type: "lead", text: "The 30-minute pitch is real on a good day — but it depends entirely on when you cross." },
      { type: "heading", id: "the-daily-commute", text: "The daily commute" },
      { type: "paragraph", text: "SENTRI-enrolled owners crossing outside peak hours routinely clear the border in 15-20 minutes; peak afternoon crossings can run well over an hour." },
      { type: "heading", id: "cost-of-living", text: "Cost of living" },
      { type: "paragraph", text: "Groceries, dining, and household help typically cost 40-60% less than San Diego equivalents, which is the single biggest lifestyle shift most new owners notice." },
      { type: "heading", id: "building-a-routine", text: "Building a routine" },
      { type: "paragraph", text: "Owners who make the split work tend to anchor their week around fixed crossing days rather than commuting daily, treating the property more like a second home with a very short flight." },
    ] as ContentBlock[],
  },
  {
    id: 8,
    slug: "first-timers-guide-notary-process",
    title: "A first-timer's guide to the Mexican notary process",
    excerpt: "The notario público plays a different role than a U.S. notary — here's what they actually verify before closing.",
    dek: "The notario público plays a different role than a U.S. notary — here's what they actually verify before you sign anything.",
    category: "Guides" as const,
    date: "Apr 2026",
    readTime: "6 min read",
    author: "Diego Alvarado",
    authorRole: "Legal & Compliance Editor",
    authorInitials: "DA",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    featured: false,
    toc: [
      { id: "not-a-us-notary", label: "Not a U.S. notary" },
      { id: "what-gets-verified", label: "What gets verified" },
      { id: "what-to-bring-to-closing", label: "What to bring to closing" },
    ],
    body: [
      { type: "lead", text: "In Mexico, a notario público is a licensed attorney appointed by the state, not a rubber-stamp witness." },
      { type: "heading", id: "not-a-us-notary", text: "Not a U.S. notary" },
      { type: "paragraph", text: "The notario is legally responsible for the accuracy of the transaction, which is why their review carries far more weight than a typical U.S. closing agent's." },
      { type: "heading", id: "what-gets-verified", text: "What gets verified" },
      { type: "paragraph", text: "Expect the notario to confirm title history, outstanding liens, zoning compliance, and that all applicable taxes have been paid before authorizing the deed." },
      { type: "heading", id: "what-to-bring-to-closing", text: "What to bring to closing" },
      { type: "paragraph", text: "Bring a valid passport, proof of immigration status (FMM or residency card), and your fideicomiso paperwork if the property sits in the restricted zone." },
    ] as ContentBlock[],
  },
  {
    id: 9,
    slug: "valle-de-guadalupe-buyers-market",
    title: "Valle de Guadalupe: Mexico's wine country is becoming a buyer's market",
    excerpt: "Vineyard-adjacent lots and boutique hospitality projects are drawing a new kind of cross-border buyer.",
    dek: "Vineyard-adjacent lots and boutique hospitality projects are drawing a new kind of cross-border buyer to Mexico's wine country.",
    category: "Neighborhoods" as const,
    date: "Mar 2026",
    readTime: "7 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&q=80",
    featured: false,
    toc: [
      { id: "why-now", label: "Why now" },
      { id: "what-is-selling", label: "What is selling" },
      { id: "things-to-check-before-you-buy", label: "Things to check before you buy" },
    ],
    body: [
      { type: "lead", text: "Valle de Guadalupe has spent a decade building a reputation as Mexico's wine country. It's only recently started building housing to match." },
      { type: "heading", id: "why-now", text: "Why now" },
      { type: "paragraph", text: "Land prices are still a fraction of comparable wine-region markets in California, even as tourism numbers climb every season." },
      { type: "heading", id: "what-is-selling", text: "What is selling" },
      { type: "paragraph", text: "The strongest demand is for view lots near established wineries and small boutique-hotel developments aimed at weekend visitors rather than full-time residents." },
      { type: "heading", id: "things-to-check-before-you-buy", text: "Things to check before you buy" },
      { type: "paragraph", text: "Water rights and well access are the two issues that most often complicate a purchase here — confirm both before you go under contract." },
    ] as ContentBlock[],
  },
  {
    id: 10,
    slug: "financing-options-for-us-citizens",
    title: "Financing options for U.S. citizens buying property in Mexico",
    excerpt: "Cross-border mortgages, developer financing, and the cash-purchase math that still wins most of the time.",
    dek: "Cross-border mortgages, developer financing, and the cash-purchase math that still wins for most buyers.",
    category: "Finance" as const,
    date: "Mar 2026",
    readTime: "5 min read",
    author: "Chris Doyle",
    authorRole: "Cross-Border Living Editor",
    authorInitials: "CD",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
    featured: false,
    toc: [
      { id: "cross-border-mortgages", label: "Cross-border mortgages" },
      { id: "developer-financing", label: "Developer financing" },
      { id: "the-cash-math", label: "The cash math" },
    ],
    body: [
      { type: "lead", text: "Financing is the part of buying in Mexico that surprises U.S. buyers most — the options exist, but they don't look like a conventional mortgage." },
      { type: "heading", id: "cross-border-mortgages", text: "Cross-border mortgages" },
      { type: "paragraph", text: "A small number of lenders now offer USD-denominated mortgages secured by Mexican property, typically at higher rates and shorter terms than U.S. financing." },
      { type: "heading", id: "developer-financing", text: "Developer financing" },
      { type: "paragraph", text: "Most **certified developers** offer their own payment plans during pre-sale, spreading 30-50% of the price over the construction period with no interest." },
      { type: "heading", id: "the-cash-math", text: "The cash math" },
      { type: "paragraph", text: "Given financing costs, a large share of buyers still pay cash — pre-sale pricing plus developer financing often works out cheaper than borrowing at current cross-border mortgage rates." },
    ] as ContentBlock[],
  },
  {
    id: 11,
    slug: "presale-condos-tijuana-outperforming",
    title: "Why pre-sale condos in Tijuana are outperforming resale",
    excerpt: "Appreciation data from the last three delivery cycles, and how to evaluate a developer's track record.",
    dek: "Appreciation data from the last three delivery cycles shows why buying early in a Tijuana pre-sale still beats waiting for resale inventory.",
    category: "Market" as const,
    date: "Mar 2026",
    readTime: "6 min read",
    author: "María Ruiz",
    authorRole: "Senior Market Analyst",
    authorInitials: "MR",
    image: "https://images.unsplash.com/photo-1504109586057-7a2ae83d1338?w=800&q=80",
    featured: false,
    toc: [
      { id: "the-appreciation-data", label: "The appreciation data" },
      { id: "why-the-gap-exists", label: "Why the gap exists" },
      { id: "evaluating-a-developers-track-record", label: "Evaluating a developer's track record" },
    ],
    body: [
      { type: "lead", text: "Buyers who bought pre-sale in Tijuana's last three delivery cycles outperformed resale buyers by a wide margin — but the gap depends heavily on which developer they chose." },
      { type: "heading", id: "the-appreciation-data", text: "The appreciation data" },
      { type: "paragraph", text: "Units purchased in the first release phase of a project have historically appreciated 15-25% by the time of delivery, before any resale market activity even begins." },
      { type: "heading", id: "why-the-gap-exists", text: "Why the gap exists" },
      { type: "paragraph", text: "Early-phase pricing reflects construction risk that resale buyers no longer have to take on, which is exactly the premium pre-sale buyers get paid to accept." },
      { type: "heading", id: "evaluating-a-developers-track-record", text: "Evaluating a developer's track record" },
      { type: "paragraph", text: "Track record matters more than price here — a developer's last two or three completed projects are the best predictor of whether a pre-sale discount is worth the wait." },
    ] as ContentBlock[],
  },
  {
    id: 12,
    slug: "remote-work-home-office-in-baja",
    title: "Remote work, real estate: setting up your home office in Baja",
    excerpt: "Internet reliability by zone, coworking spaces, and what to check before you sign a lease or close on a unit.",
    dek: "Internet reliability by zone, coworking options, and what to check before you sign a lease or close on a unit for remote work.",
    category: "Lifestyle" as const,
    date: "Feb 2026",
    readTime: "5 min read",
    author: "Chris Doyle",
    authorRole: "Cross-Border Living Editor",
    authorInitials: "CD",
    image: "https://images.unsplash.com/photo-1504615755583-2916b52192a3?w=800&q=80",
    featured: false,
    toc: [
      { id: "internet-reliability-by-zone", label: "Internet reliability by zone" },
      { id: "coworking-options", label: "Coworking options" },
      { id: "before-you-commit", label: "Before you commit" },
    ],
    body: [
      { type: "lead", text: "Remote work is one of the fastest-growing reasons Americans are buying in Baja California, and connectivity is the first thing to check." },
      { type: "heading", id: "internet-reliability-by-zone", text: "Internet reliability by zone" },
      { type: "paragraph", text: "Zona Río in Tijuana and central Rosarito have the most reliable fiber coverage; more remote coastal lots often depend on cellular hotspots as a backup." },
      { type: "heading", id: "coworking-options", text: "Coworking options" },
      { type: "paragraph", text: "A handful of coworking spaces have opened in Tijuana and Ensenada over the past two years, offering day passes for owners who want a change of scenery." },
      { type: "heading", id: "before-you-commit", text: "Before you commit" },
      { type: "paragraph", text: "Ask any developer for actual upload-speed numbers from a unit in the building, not just the advertised plan — building materials and distance from the router closet both matter." },
    ] as ContentBlock[],
  },
  {
    id: 13,
    slug: "red-flags-developer-contract",
    title: "5 red flags to check before signing any developer contract",
    excerpt: "Payment schedules, delivery penalties, and the clauses that separate a certified developer from a risky one.",
    dek: "Payment schedules, delivery penalties, and the clauses that separate a certified developer from a risky one.",
    category: "Guides" as const,
    date: "Feb 2026",
    readTime: "8 min read",
    author: "Diego Alvarado",
    authorRole: "Legal & Compliance Editor",
    authorInitials: "DA",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    featured: false,
    toc: [
      { id: "payment-schedule-red-flags", label: "Payment schedule red flags" },
      { id: "delivery-penalties", label: "Delivery penalties" },
      { id: "clauses-to-avoid", label: "Clauses to avoid" },
    ],
    body: [
      { type: "lead", text: "Most disputes with developers in Mexico trace back to a handful of contract clauses that buyers didn't push back on before signing." },
      { type: "heading", id: "payment-schedule-red-flags", text: "Payment schedule red flags" },
      { type: "paragraph", text: "Be cautious of any schedule that front-loads more than 30% of the price before groundbreaking, especially from a developer without completed projects." },
      { type: "heading", id: "delivery-penalties", text: "Delivery penalties" },
      { type: "paragraph", text: "A serious developer's contract includes a specific, enforceable penalty for missed delivery dates — vague language about 'reasonable delays' is a warning sign." },
      { type: "heading", id: "clauses-to-avoid", text: "Clauses to avoid" },
      { type: "paragraph", text: "Watch for unilateral price-escalation clauses and any language that lets the developer substitute materials or unit specifications without your written consent." },
    ] as ContentBlock[],
  },
] as const;

export type BlogPost = (typeof posts)[number];
