// Static data for the explore-map: listings, pin coordinates, and supported Mexican states.
export const listings = [
  {
    id: 1,
    status: "verified" as const,
    title: "Residencial Altamar",
    zone: "Zona Río, Tijuana",
    state: "Baja California",
    priceMXN: 4250000,
    priceUSD: 250000,
    beds: 3,
    baths: 2,
    sqft: 180,
    rating: 4.8,
    reviews: 124,
    type: "Condo",
    borderMiles: 5,
    sdSavings: 68,
    lat: 32.5149,
    lng: -117.0382,
    image: "https://res.cloudinary.com/dserzvrwe/image/upload/f_auto,q_auto/Panoramic_View_vy1spn.png",
    constructionStatus: "Ready to move in" as const,
    financingAvailable: true,
    photos: 14,
    tags: ["Homes"] as const,
  },
  {
    id: 2,
    status: "preventa" as const,
    title: "Torres Pacífico",
    zone: "Playas de Rosarito, BC",
    state: "Baja California",
    priceMXN: 3100000,
    priceUSD: 182000,
    beds: 2,
    baths: 2,
    sqft: 130,
    rating: 4.6,
    reviews: 89,
    type: "Condo",
    borderMiles: 18,
    sdSavings: 71,
    lat: 32.3667,
    lng: -117.0647,
    image: "https://res.cloudinary.com/dserzvrwe/image/upload/f_auto,q_auto/Render_Del_Mar_aynv6k.png",
    constructionStatus: "Pre-sale" as const,
    financingAvailable: true,
    photos: 10,
    tags: ["Homes", "Oceanfront"] as const,
  },
  {
    id: 3,
    status: "destacado" as const,
    title: "Hacienda Valle",
    zone: "Valle de Guadalupe, BC",
    state: "Baja California",
    priceMXN: 12800000,
    priceUSD: 750000,
    beds: 5,
    baths: 4,
    sqft: 420,
    rating: 5.0,
    reviews: 41,
    type: "House",
    borderMiles: 55,
    sdSavings: 69,
    lat: 32.0285,
    lng: -116.6005,
    image: "https://res.cloudinary.com/dserzvrwe/image/upload/f_auto,q_auto/Modern_House_White.H03.2k_sjznmv.png",
    constructionStatus: "Under construction" as const,
    financingAvailable: false,
    photos: 22,
    tags: ["Homes"] as const,
  },
  {
    id: 4,
    status: "verified" as const,
    title: "Ensenada Marina",
    zone: "Ensenada, Baja California",
    state: "Baja California",
    priceMXN: 4165000,
    priceUSD: 245000,
    beds: 3,
    baths: 2,
    sqft: 150,
    rating: 4.5,
    reviews: 102,
    type: "Condo",
    borderMiles: 68,
    sdSavings: 70,
    lat: 31.8667,
    lng: -116.5960,
    image: "https://res.cloudinary.com/dserzvrwe/image/upload/f_auto,q_auto/Panoramic_View_vy1spn.png",
    constructionStatus: "Pre-sale" as const,
    financingAvailable: true,
    photos: 9,
    tags: ["Homes", "Oceanfront"] as const,
  },
] as const;

export const CONSTRUCTION_STATUSES = ["Pre-sale", "Under construction", "Ready to move in"] as const;

export const MEXICAN_STATES = [
  "All",
  "Baja California",
  "Baja California Sur",
  "Nayarit",
  "Quintana Roo",
  "Jalisco",
  "Yucatán",
  "Oaxaca",
  "Sonora",
] as const;

export type Listing = (typeof listings)[number];
export type ListingStatus = Listing["status"];
export type ConstructionStatus = (typeof CONSTRUCTION_STATUSES)[number];
export type Currency = "USD" | "MXN";
export type MexicanState = (typeof MEXICAN_STATES)[number];
